# Clippy конфигурация
# Для использования в модуле создайте symlink:
#   ln -s ../../config/rust/clippy.toml clippy.toml
#
# Или скопируйте файл и настройте под свой проект

# Максимальная когнитивная сложность функции
cognitive-complexity-threshold = 30

# Максимальная цикломатическая сложность функции
cyclomatic-complexity-threshold = 25

# Максимальное количество строк в функции
too-many-lines-threshold = 100

# Максимальное количество аргументов функции
too-many-arguments-threshold = 7

# Максимальная длина типа для отображения в сообщениях
type-complexity-threshold = 250

# Максимальная длина строки для однострочных строк
single-char-binding-names-threshold = 4

# Максимальное количество вложенных блоков
# (Clippy не имеет прямой настройки, используйте аннотации)

# Список разрешенных имен для одиночных символов
# (по умолчанию: i, j, k, x, y, z)
# single-char-binding-names = ["i", "j", "k", "x", "y", "z", "n", "m"]
