version: '3.8'

services:
  dev:
    container_name: ${CONTAINER_NAME:-devcontainer-workspace}
    image: ghcr.io/nizovtsevnv/devcontainer-workspace:latest

    volumes:
      - ..:/workspace:cached
      # Раскомментируйте для доступа к Docker/Podman изнутри контейнера:
      # Docker:
      # - /var/run/docker.sock:/var/run/docker.sock
      # Podman (rootless):
      # - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock

    working_dir: /workspace

    # ПРИМЕЧАНИЕ: Этот файл оставлен для совместимости с VS Code DevContainers
    # Make команды (make up/down) используют нативный podman/docker напрямую
    #
    # Автоматическое использование UID/GID хоста (экспортируется в makefiles/config.mk)
    # Обеспечивает корректные права доступа между хостом и контейнером
    # Fallback: 1000:1000
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"

    # Keep container running
    command: /bin/bash -c "trap 'exit 0' TERM; while true; do sleep 1; done"

    # Graceful shutdown
    stop_grace_period: 2s

    # Environment variables
    environment:
      - INSIDE_DEVCONTAINER=1
      - USER=developer
      - HOME=/home/developer

    # Network mode for accessing host services
    network_mode: host
